#!/usr/bin/env bash

HERE=$(dirname "$(realpath "$0")")

echo "Cleaning up old skills in $HERE/.claude/skills"
rm -rf "$HERE/.claude/skills"

echo "Installing skills from $HERE/skills to $HERE/.claude/skills"
test -d "$HERE/.claude/skills" || mkdir -p "$HERE/.claude/skills"

for file in $(find ./skills -type f -name "SKILL.md"); do
    skill=$(basename "$(dirname "$file")")
    echo "Processing $skill from $file"
    mkdir -p $HERE/.claude/skills/$skill
    cp "$file" $HERE/.claude/skills/$skill/
    echo "Skill $skill installed"
done